name: Execute Python Example

on:
  push:
    branches: [ "master" ]
    paths: ['python/config/**']
  pull_request:
    branches: [ "master" ]
    paths: ['python/config/**']

permissions:
  contents: write

jobs:
  execute:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd python
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute Script
      env:
        ZIA_RATE_LIMIT: '3'
        ZIA_USERNAME: ${{ secrets.ZIA_USERNAME }}
        ZIA_PASSWORD: ${{ secrets.ZIA_PASSWORD }}
        ZIA_API_KEY: ${{ secrets.ZIA_API_KEY }}
        ZIA_CLOUD: 'https://zsapi.zscalerthree.net/api/v1'
        ZIA_USER_PASSWORD: ${{ secrets.ZIA_USER_PASSWORD }}
        OAUTH_SERVER: ${{ secrets.OAUTH_SERVER }}
        OAUTH_TOKEN_PATH: '/oauth2/default/v1/token'
        OAUTH_SCOPE: ${{ secrets.OAUTH_SCOPE }}
        OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
        OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
        PYTHONPATH: ${{ github.workspace }}
      run: |
        cd python
        python manage_config.py
    # Check if a commit is required based on updates to the DNS records and run commit
    - name: Commit State Updates
      run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -a -m "update state file"
          git push